name: Rancher S3FS based on Rexray S3FS
description: |
  Rancer volume storage plugin for S3.
version: 0.2.0
category: Storage
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle'